---
- name: Ensure myapp.virtnet is in /etc/hosts
  hosts: managed1
  become: yes
  tasks:
    - name: Add hosts entry for myapp.virtnet
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "10.0.0.123 myapp.virtnet"
        state: present
        create: yes
