---
# tasks file for fail2ban
- name: Install fail2ban
  dnf:
    name: fail2ban # Intrusion prevention
    state: latest

- name: Create fail2ban jail.local file
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local

- name: Start and enable fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes
